-- App pessoal, sem autenticação: desativa RLS em todas as tabelas
ALTER TABLE destinos DISABLE ROW LEVEL SECURITY;
ALTER TABLE transportes DISABLE ROW LEVEL SECURITY;
ALTER TABLE atracoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE gastos DISABLE ROW LEVEL SECURITY;
ALTER TABLE pendencias DISABLE ROW LEVEL SECURITY;
ALTER TABLE memorias DISABLE ROW LEVEL SECURITY;
ALTER TABLE orcamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE base_atracoes DISABLE ROW LEVEL SECURITY;
